#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed go fzf ttf-jetbrains-mono-nerd pavucontrol rofi-wayland
sudo pacman -S --noconfirm ttf-font-awesome waybar ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols
