geometry {
}

listener {
    timeout = 600                                 # 10 min
    on-timeout = brightnessctl set 10%            # dim monitor backlight
    on-resume = brightnessctl set 100%            # restore monitor backlight
}

listener {
    timeout = 1200                                # 20 min
    on-timeout = hyprlock                         # command to launch lock screen
}

listener {
    timeout = 1320                                # 22 min
    on-timeout = hyprctl dispatch dpms off        # turn off screen
    on-resume = hyprctl dispatch dpms on          # turn on screen
}

listener {
    timeout = 2400                                # 40 min
    on-timeout = systemctl suspend                # suspend PC
}

